schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "VpcEnvironmentInput"

  types:
    VpcEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_name:
          type: string
          description: "The name for your VPC"
          default: "simple-vpc-tf"
        vpc_cidr:
          type: string
          description: "This CIDR range for your VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
